// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls when reasoning summaries are delivered relative to later response items.
 */
export type ReasoningSummaryDelivery = "sequential" | "concurrent" | "concurrent_cutoff";
